swagger: '2.0'
info:
  title: TODO
  description: TODO
  version: '1.0.0'
host: /
basePath: /api
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:

definitions:
  Success:
    type: object
    properties:
      message:
        type: string
  Error:
    type: object
    properties:
      message:
        type: string
    example:
      message: Something went wrong
  ValidationError:
    type: object
    properties:
      success:
        type: boolean
      message:
        type: string
      errors:
        $ref: '#/definitions/FieldValidationError'
    example:
      message: Incorrect data
      errors:
        field1: This field is required
        field2: This field is required
  FieldValidationError:
    type: object
    properties:
      key:
        type: string
    additionalProperties:
      type: string
responses:
  Accepted:
    description: Request accepted
    schema:
      $ref: "#/definitions/Success"
  BadRequest:
    description: Request invalid
    schema:
      $ref: "#/definitions/ValidationError"
  ServerError:
    description: Server error
    schema:
      $ref: "#/definitions/Error"
